### ISSUE TITLE
Internal glass is too sharp in the corners

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#1010]
Internal glass is too sharp in the corners, is it missing some smoothness? 

![fg-0](https://user-images.githubusercontent.com/5700795/37498550-e8bb49ee-28b6-11e8-9087-aeae16bdac71.jpg)

From the outside, the glass looks really good: 

![fg-1](https://user-images.githubusercontent.com/5700795/37498556-ecf6dbe0-28b6-11e8-82e2-8619d0d7bf8a.jpg)
![fg-2](https://user-images.githubusercontent.com/5700795/37498557-ed112586-28b6-11e8-81e2-7bb733a0b231.jpg)

**Comment by wlbragg** [comment]
I fixed this and as a byproduct we got am ever so slightly improvement to the rain on glass effect overall.

![glass1](https://user-images.githubusercontent.com/11069680/37525695-8cb0e132-28fb-11e8-886e-dceec94dc0c5.jpg)
![glass2](https://user-images.githubusercontent.com/11069680/37525699-8de257c0-28fb-11e8-9e97-65b052e34547.jpg)

**Comment by wlbragg** [comment]
FYI: the issue was the front windshield interior glass layer was divided into two sections, the sides and the front. Even though the edges lined up precisely it left a hard edge. What I did was to duplicate the outside layer that is one piece and flip the normals accordingly. That fixed the front glass.
The rear sloping glass also was attached to the front glass so it was getting the effects of the prop wash, so I separated it from the front glass and assigned the side glass effects to it. That is technically not correct in as much as the side glass effect has a different mapping for the rain, but in this case it removed the bad effect of the prop wash and still looks OK compared to before. So we ended up with a net gain in visual appearance IMHO.

**Comment by wlbragg** [comment]
Oh, no, I think I messed up the entire commit and push, I am seeing the old file and effects. even in the pictures. I have to sort this out so please beware something is amiss here and not to point out the obvious...

**Comment by wlbragg** [comment]
After further review, I don't care for our reflection maps. They are nice as in they were done using blender so they are proportionally sound but they are also using Blender's rendering VS FlightGear's so we are not getting anywhere near true reflections. I think someone needs to redo them using screen shots from within the sim in the "squarest" resolution you can achieve. I think we would be better off with proportion deficits and good images of the actual FG rendered cockpit than Blender's version.

**Comment by gilbertohasnofb** [comment]
Your fix looks good.
