### ISSUE TITLE
Instruments black from exterior

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#1025]
![image](https://user-images.githubusercontent.com/10434911/37911301-96b58462-3107-11e8-8416-b651bc281e74.png)

**Comment by gilbertohasnofb** [comment]
Lego, what zoom and distance are you? The instruments go black on purpose if you are very distant, in order to improve performance. I suspect the image above was taken at very far distance + a lot of zoom. Could you please tell us how to reproduce it?

**Comment by legoboyvdlp** [comment]
Hmm... I was in helicopter mode, and using the X-key as usual. 
I merely went to helicopter mode and zoomed in.

Actually, how do you change the view disctance without actually using the dialog (which is quite hard to do )

**Comment by gilbertohasnofb** [comment]
> Actually, how do you change the view disctance without actually using the dialog (which is quite hard to do )

In the regular mouse mode, use the scroll wheel while in helicopter view.

I will test this again later today to see if all is fine but I thought all instruments would show normally at the default distance in the helicopter view.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp This bug is invalid. This is the default distance and only changing the zoom:

![fg-0](https://user-images.githubusercontent.com/5700795/37933510-574edaf8-3143-11e8-95d3-0f63a5aa62d1.jpg)

You need to be over 30m away in order for the instruments to turn black. This is 30m and 35m away and really zoomed in:

![fg-1](https://user-images.githubusercontent.com/5700795/37933518-626e6390-3143-11e8-9cc1-81fc8a690958.jpg)
![fg-2](https://user-images.githubusercontent.com/5700795/37933519-628b3b14-3143-11e8-82e8-4ca265d64b24.jpg)

With the default zoom, 35m away looks like this which is why we do this small performance optimization of blacking them out so that the instrument of far away 172s in MP do not hog down resources:

![fg-3](https://user-images.githubusercontent.com/5700795/37933540-72927b08-3143-11e8-9eca-7fa3f2c47ca2.jpg)
