### ISSUE TITLE
Cannot see text in GPS screen

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1045]
I believe that is caused by the black background color and black front color.

![fgfs-screen-430](https://user-images.githubusercontent.com/423703/38347502-76433426-38ce-11e8-967b-68d5371d2297.png)

**Comment by tonghuix** [comment]
...And also other page has strange background texture, sorry no screenshot for that.

**Comment by wlbragg** [comment]
Yeah, that really got messed up. I could have sworn it was working correctly. Well have to dig into this.

**Comment by wlbragg** [comment]
Does it just look like the background that is broken and not the GPS logic itself?

**Comment by wlbragg** [comment]
@gilbertohasnofb 
I posted on the PR what I did to fix it. I am at a loss and don't really care as long as it is correct now.

**Comment by wkitty42** [comment]
On 04/05/2018 01:22 PM, Gilberto Agostinho wrote:
> Here is a screenshot of what I see when I turn the GPS on:
> 
> file:///home/gilberto/Desktop/FG-0.jpg


ummm... we can't view a pic on your system ;) ;) ;)

it is ok, though... i've done similar dozens of times over the years :lol:

**Comment by gilbertohasnofb** [comment]
> ummm... we can't view a pic on your system ;) ;) ;)

That was a GitHub problem with the drag and drop, but I fixed that within 1 second of my post :smile:

**Comment by wkitty42** [comment]
oh! yeah, the email copies i get don't get updated like that :lol:

**Comment by gilbertohasnofb** [comment]
Yeah, forgot you do not use the GitHub interface! I find it so much better than answering by e-mail, makes the whole thread so much clearer and also adds these little reactions of :+1: :-1: :heart: :smile: or :tada: when a full reply would be not necessary.

**Comment by wkitty42** [comment]
On 04/05/2018 07:07 PM, Gilberto Agostinho wrote:
> Yeah, forgot you do not use the GitHub interface! I find it so much better than 
> answering by e-mail, makes the whole thread so much clearer and also adds these 
> little reactions of 👍 👎 ❤️ 😄 or 🎉 when a full reply would be not necessary.


well, i do sometimes but i do emails first... then my firefox stuff which starts 
off with my admin/support duties in another forum... i think my swinging by 
github is the 3rd or 4th thing in the list... that mainly to review postings and 
possibly look back but mostly just to clear them and mark them as read... i hate 
the interface because it is a real PITA to try to find a conversation again to 
add or amend it...

anyway, the FG forums come after github and somewhere in there discord is looked 
at a few times... i also have to slip in some time to read the 100+ messages a 
day posted to Fidonet which is an old school BBS network... all through all of 
this i'm jumping over to my FG which is running on another ""desktop"" on this 
linux system... i have six ""desktops"" here, all doing numerous things... my FG 
is flying something somewhere all the time... call it a stress test along with 
bug hunting :lol:

so, i run that loop several times a day all day unless i'm called out to a 
construction site to do some soil engineering tech work... yeah, that's my 
life... ain't it grand :)
