### ISSUE TITLE
Is the pitch too sensitive?

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1047]
Very little yoke movement (I believe only 5~10 millimeter) at pitch axis would cause head up and down very rapidly and abruptly, and it also cause VSI change huge amount, from ±500 to ±1000, does it real? 

I also test Cessna 337, CAP10B and DR400, these aircraft use jsbsim as well, but doesn't experience this problem. 

And c182s has the same problem too, but not so obvious and making me dizziness.

To re-produce, you have to fly longer and without AP all the time, such us fly from PHOG to PHNL, and using a accuracy joystick such T16000M.

**Comment by okroth** [comment]
Where is your CG? What you  describe sounds like pitch instability that occurs if the center of gravity is moved backwards. Usually the CG needs to be near of 25% of wing chord.
If you have high load in the baggage compartment, it could create such a behaviour.

**Comment by tonghuix** [comment]
@okroth thank you for providing a explanation!

However, I checked the fuel and payload dialog, my CG is 40.95 inch shown in the dialog. And I checked POH, the CG is in Normal Category. 

Here is my weight and balance detail:

Pilot: 180 lb 
Fuel: 40 Gallons / 240.8 lb
Gross Weight: 1887 lb

**Comment by okroth** [comment]
40.95 is only 0.45 inch behind the 25% chord, and pretty OK.
Did you open the property tree viewer and watch the elevator inputs?
In the JBSIM flight model, the elevator is "filtered" using a kinematic component, which lets the yoke travel with minimum 0.15s from full pull to full push.
That could introduce a pilot induced oscillation, as it takes some time after control input to create an effect. During this time, the lack of effect increases the input.
You could check by changing line 692 of c172p.xml from 
                <input>fcs/elevator-cmd-norm-filtered</input>
to
                <input>fcs/elevator-cmd-norm</input>

**Comment by tonghuix** [comment]
@okroth Thank you again!

After change the c172p.xml file, the pitch not such sensitive, but when console property tree with elevator input from -0.01 to +0.01, the head still up and down still, but not quickly and abruptly. 

And I also notice that when stay at ground (speed zero) with no air flow to elevator, the plane also head up and down but only response with full yoke, I found this when running up at checking flight control movement when before takeoff checklist.

**Comment by okroth** [comment]
Was the engine running?
The C172P flight model has prop wash implemented that effects pitch moment due to elevator deflection.

**Comment by tonghuix** [comment]
@okroth oh yes, engine running at ground. But I wonder the prop wash shouldn't effect the plane such obviouse.

**Comment by okroth** [comment]
The flight model uses the /propulsion/engine/prop-induced-velocity_fps property as airspeed for the elevator and rudder, not the airplane's speed. This may be over-estimating the actual value at the tail as we have a cabin in between that slows down the airstream.

**Comment by tonghuix** [comment]
I do believe the pitch still too sensitive, does anyone have experience that fly a real Cessna 172?

**Comment by okroth** [comment]
In reality the plane is flown with force not travel feedback. 
When cruising with 100kts, an elevator displacement of 8° up is sufficient to pitch the plane by 6° nose up. This results in a triple as high CL giving 3g vertical acceleration.
The 8° are achieved by moving the yoke only by 28mm.
The resulting force from the elevator's hinge moment, however, is in the 400N range (about 40kg).
Usually one uses a few 10N (a few kg) to manoeuvre the plane, resulting in small movements of the yoke. (about a few mm to cm). The rest is trimmed off.

So if your joystick is set to travel from -1 to +1, the necessary movement is indeed very small, especially as the joystick's travel will not be the +/-90 mm of the yoke.

You may like to either change the settings of the joystick, or add a function that works like the F-16 flight computer. This fly-by-wire system uses a speed squared dependent gain to the joystick input such that at any speed the same angle of joystick input creates the same aerodynamic force and therefore acceleration.

**Comment by dany93** [comment]
Thank you, @okroth for your detailed and very interesting explanations!

**Comment by dany93** [comment]
@tonghuix 
Is your joystick accurate enough? Sometimes, the potentiometers are worn and they become noisy, particularly close to the neutral, (not with Hall effect JS).
To get an idea about this, try by controlling with the mouse (which, of course, doesn't have this issue).

**Comment by tonghuix** [comment]
@okroth thank you very much!
@dany93 yes, my stick using Hall effect JS (T16000M), very very accuracy, that's why I found this question, because very small 'vibration' will cause a huge and rapidly movement on the aircraft.

Now what I have done is set a larger range of 'dead zone' near neutral, and train myself to adopt this! At least now I can fly a rectangle course in ±200 ft. well still need more practice to meet ACS in ±100 ft.

*I do trim off the plane!*

**Comment by tonghuix** [comment]
Hi, I suggest we could make the plane response pitch input not such active and fast especially in low air speed.

I found it is very odd that the pitch become more sensitive at low air speed (lower than 75kt), and less sensitive at high air speed (faster than 85kt).

**Comment by dany93** [comment]
> I found it is very odd that the pitch become more sensitive at low air speed (lower than 75kt), and less sensitive at high air speed (faster than 85kt).

I don't find this.
At low airspeed, throttle it up makes it more sensitive, but we need at worst same elevator amplitudes at high regime low airspeed, and more elevator amplitude at low regime. Never less elevator amplitude at lower speeds.

At idle aiming at stall in horizontal flight (without flaps), I need 80 - 90% elevator up just before stall.

@okroth, could you try it and give your opinion about this elevator sensitivity?

**Comment by tonghuix** [comment]
Yes, I also use nearly full displacements at low speed, but the sensitively not triggered by displacements also by small movement.

**Comment by tonghuix** [comment]
Here is a SOP for experience this effect: 
0. Take off and climb above 1500ft.
1. Set 1500 RPM and maintain altitude
2. Set landing configuration (flap full)
3. Maintain altitude and slow to approximately 45-50 kt just 5-10 above VS0 stall speed. Avoid stall warning activation
4. Engine power as required to maintain airspeed
5. Accomplish *level flight*,* climbs*, *turns*, and *descents*
6. Recover

Try to feel the sensitive and control efficiency during the slow flight.

**Comment by okroth** [comment]
First: I used the mouse as flight control.. no force feedback ;-)
Second: flew with 45kt and flaps fully extended. But had more than 1500 rpm.
How can you steadily fly with 1500 rpm and 45kts? With that settings I had a sink rate of 300fpm.
(Which is realistic) Any pull squeaked the stall horn.
Nevertheless, control input reactions were as I would expect them; sluggishly, not critical.
Check your joystick, it may have worn out.
And do not fly that dangerously. In real life you fly full flaps at final approach only, with appropriate sink rate. Actually full flaps only if you approach a airport with short runway. Normal airports with 20° flaps. Reason: with full flaps, there is no real flare, it just sits down; so the approach must be quite precise.
No theory, experience.

**Comment by tonghuix** [comment]
1500 RPM is only a reference to reduce power.

And the landing configuration (full flap extension for c172) slow flight is a check item in ACS of FAA PPL. I believe it could also usable for FG.

**Comment by okroth** [comment]
OK,

now that manoeuvre makes sense. With about 1950rpm level flight is possible.
I did not notice an instability in pitch, however, the plane seems to flat-spin quite easily.

**Comment by algefaen** [comment]
(Re slow flight sensitivity)
> Try to feel the sensitive and control efficiency during the slow flight.

On a C172 I think you'd mainly notice the sluggishness of ailerons and not so much the elevator, since it requires quite a bit of power (->propwash) to maintain altitude at slow flight speeds. As a skydiver I can testify that the air is moving _significantly_ faster in the propwash compared to the surrounding air. (=

I wish I had a good non-destructive, non-hazardous method for logging control input + airspeeds, engine parameters, aoa, etc. in our steam gauge cessna...

**Comment by tonghuix** [comment]
I just found a lot of nice videos in a C172R (yes not P, but still could be a reference), in these videos, pilot installed a GoPro camera in front of his chest, and it record his control of yoke and the plane's reaction.

https://www.youtube.com/watch?v=WTvh_J0skWo

https://www.youtube.com/watch?v=AKkmmICGsFM

I found the plane reaction very sluggish than C172P-detailed, not only pitch but also roll.

**Comment by okroth** [comment]
nice finding!
See that even with sluggish reactions, the movement of the yoke for roll is small (only 10° ... 15° turn)

**Comment by tonghuix** [comment]
@okroth Yep, so I think it could be a bug in this c172p-detailed or in FDM.

It would add some dynamic delay for yoke input, and at slow flight add more delay.

**Comment by dany93** [comment]
@tonghuix, I think that we didn't understand it by the same way.
I read:
>  the movement of the yoke for roll is small (only 10° ... 15° turn)

Which makes 11 to 17% of full deviation.
Am I misunderstanding the message?

**Comment by dany93** [comment]
@tonghuix,

I have no problems at controlling the aircraft.
However, I've made tests and it seems that the aileron authority might be decreased a bit.
I almost sure it will improve for you, but this is to be tested and validated in enough different conditions (15 - 20 kt crosswind landing, severe turbulences,...).

In c172p.xml, line 1476, try this
Replace the initial value (0.2290) for 0.15 as shown below:
```
            <function name="aero/coefficient/ClDa">
                <description>Roll_moment_due_to_aileron</description>
                <product>
                    <property>aero/qbar-psf</property>
                    <property>metrics/Sw-sqft</property>
                    <property>metrics/bw-ft</property>
                    <property>fcs/aileron-pos-rad-avgd</property>
                    <value>0.15</value> <!-- ini 0.2290, 12 april 2017 -->
```

Do a backup copy of your initial file before, and, if you are using git, restore with the initial one before pulling.

**Comment by dany93** [comment]
For pitch I see no good solution for you in the aircraft files.
You can try to decrease the value (initial -1.8)
line 1606
```
            <function name="aero/coefficient/Cmde">
                <description>Pitch_moment_due_to_elevator_deflection</description>
                <product>
                    <property>aero/function/qbar-induced-psf</property>
                    <property>metrics/Sw-sqft</property>
                    <property>metrics/cbarw-ft</property>
                    <property>fcs/elevator-pos-rad</property>
                    <value>-1.8</value>
```
But you will see that the risk is of no longer being able to reach the stall AoA.
At low speed for landing, you want to do the flare, pull the yoke full, the aircraft will not pitch up enough.

The other way is to apply a `<power>` to your JS elevator axis. Starting by `<power>2`.

**Comment by tonghuix** [comment]
More video:

- A whole traffic pattern, with a roof-installed GoPro camera  https://www.youtube.com/watch?v=Rs1b7uSdCu8

- A beautiful girl's first solo, multi-camera,  https://www.youtube.com/watch?v=3jfRs2xsjtc&t=50s

These two videos show pitch and roll are all sluggish, I still suggest add 'delay' to yoke controls, but not rudder.

**Comment by okroth** [comment]
I have tried to find some FDM coefficients of the C172 from the Internet; the major reference seems to be some data from Roskams Book "Methods for Estimating Stability and Control Derivatives of Conventional Subsonic Airplanes", as others refer to it, namely the UIUC icing model.
Another author David Allerton had in the files accompanying his book "Principles of Flight Simulation" a FDM of the C172 with slightly deviating coefficients.

There seems to be a typo in the coefficient Cnda "yaw from aileron deflection" in the C172P, and C172R. It is -0.0053 instead of -0.053 as in Roskam and Alerton's models.
You picked it up and doubled it to -0.016 (to compensate the -2,...,+2 range of the summed ailerons), however I think it should be -0.16. With your current value it will fly nicely, but 10 times nicer as the real thing.

Your FDM is the only that has Clp = -0.968, which is double the -0.47 (or -0.484) used elsewhere.
This will slow rolling rate significantly (50%).

All other FDMs use Cmde = -1.28. A Cmde of -0.18 definitively makes the plane too sensitive to elevator.

The side force from rudder CYdr is set to 0.15 in your FDM, the value used by anyone else is 0.187. 

You aileron authority Clda is 0.229 (compensated by the -2,...+2 range this is 0.115), which again is significantly smaller than the 0.178 used by the others.

Together we have reduced rudder side effects, aileron response(64%), roll rate(50%), drastically reduced adverse yaw(10%), and increased pitch(140%).

I think, tonghuix was right in saying that pitch is too sensitive. It is just that his joystick may have too much gain on top.

**Comment by dany93** [comment]
Thank you very much @okroth for this research and indications.
I'm looking at that.

**Comment by okroth** [comment]
Oh,
do I read Cessna 1**8**2? I always thought the coefficients were computed for a Cessna 1**7**2

**Comment by dany93** [comment]
Yes, Megginson's table data are written for Cessna 1**8**2.
David Megginson took almost (if not all) of these coefficients for his Cessna 172 FDM. My tendency is to trust him (anyway, he is much better than I am on this). Probably that he had no other set?
I discovered these tables only a certain time after the C172 FDM.

**Comment by okroth** [comment]
Found some comparisons. The C182 has 1" **shorter** wingspan, 1 sqft **less** wing area, and is 2" longer. It has a larger engine, constant speed prop, and higher weight. I presume the 2" additional length go into the cowling that incorporates six cylinders compared to the 4 in the C172. So, Megginson was quite right to use the C182 coefficients. But we should consider to adjust Iyy and Izz as these are affected by the heavier engine. Iyy should be fine as this is largely dominated by the wings's weight.

**Comment by okroth** [comment]
The section 6 of the POHs gave some information:

C182P:
empty weight:1772lbs, moment:63300lbs-inch -> CG is 63300/1772=35.7in aft datum
engine O-470-U 442lbs @ 17.5 in fore datum.
This is 270slug-ft²

C172P:
empty weight:1467lbs, moment:57300lbs-inch -> CG is 39in aft datum
engine O-320-D2J 281.5lbs @ 19.6 in fore datum.
This is 209slug-ft²

C172R:
empty weight:1639lbs, moment:64400lbs-inch -> CG is 39.3in aft datum
engine IO-320-L2A 297.8lbs @ 18.6 in fore datum.
This is 215slug-ft²

So for C172P, Ixx and Izz get (270-209) = 61slug-ft² smaller
For C172R, these inertias are reduced by 55slug-ft²

**Comment by dany93** [comment]
Many thanks once more @okroth, for these informations and (more) having done and detailed the calculations.

In principle I can do these calculations (I have a table for this) but, between the units, CG shift and everything, there is more than enough to stumble.
I checked them just to be sure that I understood well that you mean, but having your values as a reference was very precious.

**Comment by dany93** [comment]
I have changed a few aerodynamic coefficients.

@okroth : Sorry to sollicitate you as much, but do you have the possibility to test the aircraft in FG? Part of this is subjective, based on memory and, when someone complains, I'm not the better one to decide. 

CnDa: -0.16 is impossible. Even -0.053 is way too much. I have set it at -0.03. Do you feel it's correct?
The irony is that I was led to decrease it because some people complained that the adverse yaw was excessive... I hope that you judgement will help to arbitrate.

Clp: It was -0.484 at ordinary roll rates (up to 5 rd/s), then (only at higher roll rates, to avoid FDM divergence) -0.968 to -1. I've set it at 0.484.

Cmde: changed (decreased) for -1.28.
However, with this value, the stall AoA could no longer be reached (at least with the pilot alone). I recovered this possibility by moving the AERORP a bit foreward (closer to the CG). It seems enough in most situations to reach stall AoA (although with a weak or no margin), but not in a turn with the engine at idle. Do you think that is enough for the stall behaviour, or do I have still to move the AERORP forward? (I'm tempted to do this). Megginson had put it even closer to the CG (at 2.2 inches). I am at 5 inches: AERORP = 44 for CG 39.06.

CYdr: If I remember well, this value had been decreased (by me, after discussions on the forum) to be fitted with the rudder moment.

ClDa. I'm confused about what you are meaning. 0.229 (current value) is the value in Megginson's table, higher (not smaller) than 0.178. However, after my tests, I think that it can be decreased down to about 0.15 without drawback, which would make it less sensitive to the ailerons. I've set it at 0.178.

Moment of inertia: decreased Iyy and Izz after your indications. I think it is not sensitive, but at least it is more rigorous.

There is probably some more refinements to be done (trim presets, maybe more on stall behavior...) but prior to spending more time on this details, I'd prefer having your opinion about the most important points.

Still thank you,
I've added your nickname in the FDM file.

**Comment by okroth** [comment]
First: Megginson has three setups: climb, cruise, and approach, with partly different coefficients.

CnDa: Megginson has -0.0504, -0.0216, -0.0786 for climb, cruise, approach... not sure why they differ, but the C172 does have adverse yaw...UIUC, Roskam, etc all use -0.053.

Clp: 5rad/s is quite a lot ~ 285°/s. All other models (I found) use -0.47...-0.494.

CmDe: FlightGear says about AERORP "the location where the aerodynamic forces are applied to the model".
I would expect this to be the 25% line of the wing. According to the POH, this is 25.9 + 0,25*58.8 inches aft datum, i.e. 40.6 inches. That would explain why you can not stall, as the allowed CG range is about 5" fore and 8" aft this point, and when you set it at 44", and fly alone with full tanks, your CG will be too far ahead.

CYDr: I will check. However, it looks as if it uses lv-ft which is <vtailarm> in the metrics section:
CYdr * lv-ft = Cndr * bw-ft 
And lv-ft is a little greater than lh-ft, as the fin is slanted backwards which shifts the aeromatic center back too.

ClDa: Megginson has -0.229 consistently. Roskam had -0.178. I think I will make an estimation using XFOIL and spreadsheet... That went quite well with the rudder hinge moments.

Regarding stall (and spin entry): you may have to consider yaw rate as this is the way to change from one to other. I.e. near stall AoA, the wing yawing forward has a lower AoA, higher lift, higher roll moment (from lift), and less drag. As long both roll moments (from lift) are balanced, the plane will not spiral off. As soon only one wing stalls, the roll moment of the other will push the plane over.

**Comment by dany93** [comment]
Thank you, @okroth 

At least for the easiest, the AERORP at 40.6 seems to work very well, I recover "my" aircraft, with its stall and spin behavior. Possibly even a bit hard, I have to see it (I think I can refine).
Very pleasant to fly.

I was afraid for the CG which can be aft the AERORP, but no problem with CG at 44.5 in.

**Comment by okroth** [comment]
CG may be behind AERORP, it must however be in front of the airplane's neutral point, which can be computed easily using the areas of stabilizer and wing an the horizontal lever arm. In a C172, it is 20.7 in behind the 25% line of the wing, so you still have plenty of space.
Nevertheless you got an experience in load and balance :-)

Regarding Ixx and Izz: The 180HP and 160HP engine are the same, the 180HP just has a higher max .RPM. So at least that can be handled easily.

**Comment by dany93** [comment]
[New version](https://github.com/c172p-team/c172p-detailed/pull/1063#issuecomment-382803664) with your indications.
With them, I'm learning here, consolidating my knowledge there. Very interesting.
Thank you.

**Comment by wlbragg** [comment]
I like the change, definitely not so sensitive yet I still have a good range of motion. Stall is good!

**Comment by onox** [comment]
@dany93 Can you update the first comment (or add a new one) of #958 ?

**Comment by dany93** [comment]
Thank you @onox, thank you @wlbragg.
https://github.com/c172p-team/c172p-detailed/issues/958 updated. If you can have a look to check the formulation, thanks.
