### ISSUE TITLE
FDM: Enhance pitch behavior when flap extended

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1073]
Quoted from 'Airplane Flying Handbook' by FAA:

> Flap extension has a definite effect on the airplane’s pitch behavior. The increased camber from flap deflection produces lift primarily on the rear portion of the wing. This produces a nose-down pitching moment; however, the change in tail loads from the downwash deflected by the flaps over the horizontal tail has a significant influence on the pitching moment. Consequently, pitch behavior depends on the design features of the particular airplane.

Because of this, in C172 when flap just extended, the plane will nose up immediately, but will nose down soon. Pilot should push nose down and up to counteract flap effect synchronously maintaining in normal approach path.

**Comment by dany93** [comment]
More complicated:
- More lift ==> nose up,
- On the rear portion of the wing ==> nose down,
- More drag + high-wings ==> nose up,
- Deflected downwash on the taii ==> nose up.

**Comment by tonghuix** [comment]
Yep more nose down, but first nose up very immediately and obviously.

**Comment by dany93** [comment]
Our C172?
I disagree.
If you stabilize it with no flaps (well trimmed, JS at neutrals, level flight with engine, or descending with engine at idle), the first thing it does at flap extension is nose down. Followed by oscillations, with lower nose attitude.

**Comment by dany93** [comment]
My test above was done with a small change on the FDM (a version in test that you don't have).
With the current master version, I observe a very small hesitation, with a _tiny_ nose upwards, followed by the frank stabilization towards nose down.

Which shows how much this is complicated...

**Comment by tonghuix** [comment]
NO NO NO NO, please reference this video
https://www.youtube.com/watch?v=pRZjr_e5MuY

**Comment by dany93** [comment]
OK for the video.

**Comment by tonghuix** [comment]
This video will demonstrate a whole normal landing (I believe it is a C172R with G1000) https://www.youtube.com/watch?v=E7-rqMLasWE&t=42s

**Comment by dany93** [comment]
The `<value>0.7` common factor is here on purpose, rather than changing every value in the table.
The pitching effect is sensitive to several parameters:
- airspeed,
- loading (e.g. copilot),
- FDM parameters.

Thus, to make adjustments easier, this common factor.
It may disappear in the future after stabilization (although I feel it  doesn't matter).  

We currently have a single video as a reference for the amplitude of the pitching, but we must be aware that the final result is complicated to analyze, then may be much arguable.

All the more that I will probably propose small changes in the FDM, which will need another value for this effect.

**Comment by wlbragg** [comment]
@dany93 a quick search actually tends to partially verify this and the reasons why.
http://www.askacfi.com/7370/why-does-a-nose-down-pitch-change-result-from-the-extension-of-flaps.htm
Search params "cessna pitch change do to flaps"
