### ISSUE TITLE
Cowling should protrude around the edges

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#1081]
I apologize for bringing up an exterior issue, but I think it would be nice to make the cowling look like a piece of metal kind of above the rest of the fuselage. The cowling is probably about 3-4mm out from the rest of the fuselage as seen in the images in #1080. I am not explaining this well, but I'll make a diagram some time showing what I mean.

**Comment by legoboyvdlp** [comment]
https://user-images.githubusercontent.com/423703/39669762-da5a86dc-5127-11e8-9060-cb732f8e83f7.JPG

**Comment by legoboyvdlp** [comment]
The cowling has two parts, an upper and lower parts as seen in that photo. You can see that the metal is set out a bit from the rest of the fuselage.

**Comment by wlbragg** [comment]
The issue with these types of changes is that it affects the UV mapping and thus is really difficult to achieve. These type of structural modifications should be done prior to the initial UV mapping. However it is good to note it here as someday we hope to have a modeler come along and model us a new aircraft.
I'll at least take a look at the feasibility, but I wouldn't hold your breath. :smile:

**Comment by tonghuix** [comment]
I don't think it is such difficult, but may only bigger 2~4 mm is okay. and may not effect UV mapping such obvious.

**Comment by wlbragg** [comment]
@tonghuix can you find me a good image of the cowling from the front underside view? I need to see the area around the radiator.

**Comment by gilbertohasnofb** [comment]
Here are some more shots that might be helpful:

![_dsc7991](https://user-images.githubusercontent.com/5700795/39699617-e1d13f4e-51f1-11e8-8318-33dc939fcc90.jpg)

![_dsc8029](https://user-images.githubusercontent.com/5700795/39699618-e1ef15dc-51f1-11e8-8bf4-4bfa57ccc696.jpg)

![](http://sky4buy.com/img/1964-Cessna-150-D-271840697267/8.jpg)

![](http://imgproc.airliners.net/photos/airliners/3/4/1/4367143.jpg?v=v42062286004)

**Comment by dany93** [comment]
That's very common.
Two pieces of steel sheet, one above, one underneath, held with screws all along the edges. Covering the main part (rear, cockpit side) on 2 or 3 cm. hence the extra thickness.
The upper one must be easy to take down for almost daily checks.

But if it is too difficult when compared with the importance (e.g. if it needs to redo the UV mapping) wouldn't a texture along the edge be enough to give the illusion?

**Comment by gilbertohasnofb** [comment]
> wouldn't a texture along the edge be easier and enough to give the illusion?

That's an option and I could give it a try if @wlbragg thinks that the 3D route isn't a good one. The problem is how the nose is UV-mapped: each side and the top nose are different parts so connecting a line between them is extremely time consuming and often I was not able to perfectly get things straight between them (e.g. when a livery would call for a lot of details in that area).

**Comment by wlbragg** [comment]
I pushed a 3d option. I check some of the more complicated liveries and I think they look great. I hope everyone agrees. It required more than you can visually see. In order to keep visual artifacts like seeing through seams, because we have a one-sided fuselage mesh, on the interior engine compartment the cowling's have 90 degree angled mesh  edges on the interior. This allowed for the increase in size without causing visible gaps in the seams. Plus all the interior compartments used to hide the fact that the fuselage is one-sided had to be temporarily joined and then re-separated again while sizing the cowlings. I am very pleased with the outcome.

**Comment by gilbertohasnofb** [comment]
@wlbragg One more good reference just in case:

![](https://i.ytimg.com/vi/gxQNnTxKYZM/maxresdefault.jpg)

**Comment by legoboyvdlp** [comment]
Excellent! Thank you :)

**Comment by legoboyvdlp** [comment]
Wlbragg, is it too late to revisit this (even in the future)?

![image](https://user-images.githubusercontent.com/10434911/39923438-6fd1b7a2-551b-11e8-92ff-3a766a3c6049.png)
I still think that the cowling is a little too thick at the bottom.

If you look at 
![image](https://user-images.githubusercontent.com/10434911/39923461-997c2934-551b-11e8-91b5-dde8c6bd78e9.png)

This appears to me as if it is about 2cm at the widest part. While, if you look at the references, it would appear that the gap actually gets smaller at the bottom of the fuselage.

**Comment by wlbragg** [comment]
@legoboyvdlp sure we can. A couple things to consider. The amount that protrudes is roughly the same as it has always been. When you first called this out it was protruded even more because of the way I enlarged cowling all around. But after your comment I did try to reduce that part, at least back to where it was originally. So just know that for one. In my opinion, that last reference image is not a good example because it is from the wrong angle. I recall seeing images of this and my recollection is that it did protrude significantly more than the rest. Unless that was just an illusion, So I would suggest more reference images from the back side angle if you can find any. I'm not saying it is perfect, it may need to be reduced some, but I would like to see it from the other angle.

**Comment by legoboyvdlp** [comment]
I understand, thank you. I'll see what I can find!

**Comment by algefaen** [comment]
@legoboyvdlp / @wlbragg : I bring [gifts](https://www.youtube.com/watch?v=Dr8JmF81MKI ). (Although this is a 172N, not P, I don't think it matters much.) ... So I think we're pretty close today. (=

**Comment by gilbertohasnofb** [comment]
@algefaen That's excellent, thank you so much!!
