### ISSUE TITLE
Small improvements to the exterior 3D model

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#259]
Create a hole for the wheels inside fairings:

![unbenannt](https://cloud.githubusercontent.com/assets/12293276/8025744/418379e4-0d61-11e5-9b3e-12cd0ba2787a.JPG)

Create a door handle:

![unbenannt](https://cloud.githubusercontent.com/assets/12293276/8025754/7f0a4b80-0d61-11e5-8468-c21bf8385b55.JPG)

**Comment by tigert** [comment]
Closeup of the door handle  - sorry I shot just one and it turned out blurry. I think the resolution might be enough for the texture use, anyway, and you can see the appearance. The handle is chromed, and it opens by lifting the edge towards the nose of the aircraft up - the handle rotates out maybe 45 degrees.

http://tigert.1g.fi/kuvat/Simulators/Flightgear/c172-details/20150527_0062.jpg

There are some closeups of the nose, wing and wheel fairings here too:

http://tigert.1g.fi/kuvat/Simulators/Flightgear/c172-details/

**Comment by gilbertohasnofb** [comment]
@tigert thanks for the pics. As for the nose, it will go through a major rework later (see: https://github.com/Juanvvc/c172p-detailed/issues/6 and https://github.com/Juanvvc/c172p-detailed/issues/216).

**Comment by gilbertohasnofb** [comment]
Also, to the 3D modellers our there: just let me know if any new texture is needed, ok? Then I can either use tigert's images above as source or simply create them myself.

**Comment by thevirtualfer** [comment]
@tigert.

Have you a photo for the engine cowl from the top view ?

**Comment by onox** [comment]
http://tigert.1g.fi/kuvat/Simulators/Flightgear/
http://tigert.1g.fi/kuvat/Simulators/Flightgear/c172-details/
http://tigert.1g.fi/kuvat/Simulators/Flightgear/C172-dimensions/
http://tigert.1g.fi/kuvat/Simulators/Flightgear/gauge-faces/

**Comment by legoboyvdlp** [comment]
@thevirtualfer , you wouldn't have done these, would you?

**Comment by gilbertohasnofb** [comment]
See https://github.com/Juanvvc/c172p-detailed/issues/622#issuecomment-166703266
