### ISSUE TITLE
Extend the paintkit to the interior

### ISSUE THREAD

**Issue by thevirtualfer** [c172p-team/c172p-detailed#448]
It is just to think about, not a urgent thing to do.

But the livery making is so limited adding texture only to the exterior. I don't know if a theme is related to both, exterior and interior. But maybe we need just think about it.

**Comment by gilbertohasnofb** [comment]
I don't really understand what you mean. Right now you can have changes to BOTH interior and exterior, so that different liveries have different colours in the panel, seats, etc. But currently it's also super easy to simply create an external livery and not bother with the interior (and use the default one). What is the issue you are seeing here?

**Comment by thevirtualfer** [comment]
I mean that when some go to the paintkit folders, there are files that helps creating exterior textures.
IMHO, there should be files that helps create the interior textures.

> But currently it's also super easy to simply create an external livery and not bother with the interior

And should be as super easy do the inverse. Create the interior texture and not bother with the exterior.

It is just a idea.

**Comment by gilbertohasnofb** [comment]
Oh, so you meant we should create a paint kit as a xcf file for the interior? Now I understand what you proposed, and that's indeed a cool idea.

**Comment by gilbertohasnofb** [comment]
@onox I think we can close this as a won't fix, since creating a xcf paintkit of the interior will be _extremely_ time consuming given that it was created step by step (unlike the exterior ones), and anyone in the future wanting to tweak or create a new one can very well use my xcf files in the Textures repo. Do you agree?

**Comment by tonghuix** [comment]
Agree won't fix, but don't close the issue.

**Comment by gilbertohasnofb** [comment]
? That doesn't make sense, if it's a won't fix then our team will certainly close this.

**Comment by onox** [comment]
@gilbertohasnofb Maybe you could add a link to your textures repo in some `README.md` file in either the `Paintkit` or `Models/Liveries` folder?

**Comment by onox** [comment]
Oh, it seems there's already a link in the main `README.md` file. I'll close this issue then.
