### ISSUE TITLE
Create control wheel lock

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#865]
Create and implement control wheel lock:

![](http://www.cessna150.net/Assets/Photos/inside_photos/controllock.JPG)

**Comment by gilbertohasnofb** [comment]
Volunteers for the 3D model? I can work on texture + XML.

**Comment by gilbertohasnofb** [comment]
@dg-505 let's continue our talk about the lock over here

**Comment by gilbertohasnofb** [comment]
I created the texture, what do you think?

![control-lock](https://cloud.githubusercontent.com/assets/5700795/20351871/35238afa-ac15-11e6-9e97-a304340683ad.png)

**Comment by dg-505** [comment]
I think when it comes to textures (and screenshots) you're really a magician  😆

**Comment by gilbertohasnofb** [comment]
Thanks a lot, Jonathan! I really appreciate it :smiley:

**Comment by gilbertohasnofb** [comment]
Here is one more idea: let's have two identical models of the lock, one positioned at the yoke, another in the pocket on the left side of the cockpit where the checklist is. So when the lock is on the yoke, clicking on it will remove it and put it on the pocket, and clicking on the lock on the pocket will put it back to the yoke. This was done by A2A, see the following video at 6:06 https://www.youtube.com/watch?v=CtFXPuklLB8

Also, when implementing the code we can't forget to deal with hide/show yokes and the lock. I would say that if one hides the yoke, the lock should be set to removed (and so go to the pocket). This is to avoid the problem of someone hiding the yoke while locked, then not being able to fly any longer and not knowing why.

What do you think?

**Comment by wlbragg** [comment]
I suppose I can create the model in Blender. Has anyone else volunteered yet?

>What do you think?

Great ideas!

**Comment by gilbertohasnofb** [comment]
@wlbragg if I understood correctly @dg-505 had volunteered to model this, am I right Jonathan?

**Comment by dg-505** [comment]
At least can give it a try. I think such a small piece can be a good way to learn Blender...

**Comment by wlbragg** [comment]
:+1:

**Comment by onox** [comment]
Here is a bunch of keys I find useful in Blender:

`t` to show panel on the left (it contains a combobox called "Set Origin")
`n` to show panel on the right (it contains 3D cursor)
`shift`+`c` to set 3D cursor to 0,0,0
`shift`+`s` -> `Cursor to Selected`
`1`, `3`, `7` (+ `shift` optionally) to show front/right/top side
`alt`+`home` to move view to 3D cursor (especially useful if you first do `shift`+`s`)
`tab` to switch between object/edit mode
`g` to move
`s` to scale
`r` to rotate
`x` to delete
You can also type `g`, `x` to move along X axis, for example. Same for `s` and `r`.
You can type `g` and `s` twice (for example: `g`, `g`) to restrict the moving/scaling in a certain way.
In edit mode you can type `a` to (un)select everything
`shift`+`rmb` (right mouse button) to select a vertex
To merge two vertices, select them, then press `alt`+`m`
Select 3 vertices and then press `f` to create a face
To select a part in an object, select one of its vertices, then press `ctrl`+`l` (L)
If you have some vertices/edges/faces selected, press `p` to separate them and put them in a new object in the outline tree.
To combine two objects, select them in the outline tree, then press `ctrl`+`j`.
To parent A an object B, select A and then B, and then press `ctrl`+`p`.
If you don't like the middle mouse button (mine works crappy because it can move a bit to the left/right), go to 'User Preferences' -> `Input`, then select 'Emulate 3 Button Mouse'. It allows you to use `alt`+`lmb` (left mosue button) instead. For me it makes it much easier to move the camera.
If you have multiple editors like '3D View' and 'Timeline' next to each other, and you want to get rid of one of them. Right click on the line between the two editors, choose 'Join Area', and then click on the editor you want to remove.

**Comment by dg-505** [comment]
@onox thank you, that is very helpfull

Here's the current progress:
![control-lock blend](https://cloud.githubusercontent.com/assets/12293276/20443858/07a77404-adcf-11e6-81c2-20301fc2cf7c.png)

Any thoughts? :smirk:

**Comment by gilbertohasnofb** [comment]
@dg-505 that looks _really_ good :smile: But are you including the yoke mount just as reference or do you plan to somehow rework the yoke model as well?

**Comment by dg-505** [comment]
Hehe, no, the mount is only there as reference :wink:

**Comment by dg-505** [comment]
Well, I could cut this hole into the mount and the yoke rod where the control lock gets sticked in...

**Comment by gilbertohasnofb** [comment]
Yes, please do that, it would look good.

**Comment by dg-505** [comment]
Roger :+1:

**Comment by dg-505** [comment]
See #874 for the 3D models

**Comment by dg-505** [comment]
Should be closed via #874
