### ISSUE TITLE
Fire extinguisher not affected by shadows:

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#872]
Fire extinguisher not affected by shadows:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/20410464/728ba9dc-ad1d-11e6-9927-d81a82afd38c.png)

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/20410465/7290e7d0-ad1d-11e6-91b4-099d3f289e8d.png)

**Comment by gilbertohasnofb** [comment]
I suspect the same is true for the other fire extinguisher (used by some of the bush variations), the two baggages and the ELT in the back of the cabin.

@wlbragg do you think you could take a look at this, or tell me how to fix this? I thought the shadow cube would be enabled similarly to the irradiance effect by using ...

````
    <effect>
        <inherits-from>../../../../Effects/interior/c172p-interior-radiance</inherits-from>
        ...
````

... but that is not the case apparently.

**Comment by wlbragg** [comment]
>@wlbragg do you think you could take a look at this, 

I don't mind fixing it (I actually did and created a bug-872 branch) except I can't seem to push. My credentials keep failing, yet I can change them in my account?

>or tell me how to fix this?

So. I think all it needs is to change
./../../../Effects/interior/c172p-interior-radiance
to 
./../../../Effects/interior/c172p-interior
The first uses the white cube and no shadow, the latter uses the shadow cube. Beware, testing and the final effect may not match the shadow in the cockpit because it is in a different space, same reason we don't use the shadow on most of the knobs and gauge faces.

We've talked about eventually trying to line up the sub-model .ac to match the local coordinates to illuminate this undesirable effect.

**Comment by wlbragg** [comment]
I finally got it to push....

**Comment by gilbertohasnofb** [comment]
> We've talked about eventually trying to line up the sub-model .ac to match the local coordinates to illuminate this undesirable effect.

**Comment by gilbertohasnofb** [comment]
> We've talked about eventually trying to line up the sub-model .ac to match the local coordinates to illuminate this undesirable effect.

That would be great. Do we have an open issue for that?

**Comment by wlbragg** [comment]
Yes, absolute position for instruments in individual .ac files #790

**Comment by onox** [comment]
Corresponding PR was merged. Closing issue.
