### ISSUE TITLE
C172p nasal runtime error in Multiplayer

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#914]
This has been reported [in the forum](https://forum.flightgear.org/viewtopic.php?f=4&t=31907) by the user jsb:

> I just saw the following by chance as a C172 entered my area in MP:
> 
> ```
>     Nasal runtime error: nil used in numeric context
>       at /fgdata/Nasal/bits.nas, line 8
>       called from: /fgdata/Aircraft/c172p/Models/c172p.ac, line 36
>       called from: /fgdata/Nasal/globals.nas, line 119
>     c172p livery update
> ```
> 
> A quick&dirty hack to avoid this is to edit /fgdata/Aircraft/c172p/Models/c172p.xml (find line 36 in the nasal block)
> Guestimate: node.getValue does not return a number -> hack: add "or 0" to line so a NIL becomes a 0.
> I leave it to the experts to decide a reasonable fallback value or track and fix the root cause of this problem :)
> 
> ```
>                 setlistener(pax_state_path, func (node) {
>                     var state = node.getValue() or 0;
>                     co_pilot.setBoolValue(bits.test(state, 0));
>                     left_passenger.setBoolValue(bits.test(state, 1));
>                     right_passenger.setBoolValue(bits.test(state, 2));
>                     pilot.setBoolValue(bits.test(state, 3));
>                 }, 1, 0);
> ```

**Comment by onox** [comment]
I think this is because some properties might not be transferred in each MP packet (we (I) kinda assumed all properties would be transferred. So adding `or 0` is a reasonable fallback.

**Comment by onox** [comment]
I'm not sure we should apply this workaround. The reason is that the c172p sends too many properties for the current MP protocol. If you try to send a MP chat message for example, you will see that FG is unable to transmit some of the properties (the packet gets truncated).

The only proper fix is to make the MP protocol more efficient, which is what Richard has done. In FG 2017.2 you can choose the compatibility mode in the Multiplayer Settings. If you choose "Visible to 2017.2+" then packets will not get truncated.
