### ISSUE TITLE
Sounds --> C152 (exterior) engine at idle

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#941]
May help you, may not. Feel free to use it or edit it or delete it. I hereby release this sound file under the GNU GPL 2.0 license.
(uploading to dropbox, stby)

**Comment by legoboyvdlp** [comment]
https://www.dropbox.com/s/cku0025x63nizo7/VID_20170423_153130753.mp4?dl=0

**Comment by tonghuix** [comment]
It seems no one deal with this project?

**Comment by gilbertohasnofb** [comment]
> It seems no one deal with this project?

Do you mean with this specific issue or with the c172p project as a whole? We are all still here, but everyone seem to be quite busy at the moment with RL or other projects. Lately most work has been minor bug fixes rather than large feature implementations for that same reason.

But if you or anyone else would like to give it a go then I would be happy to review any PRs for any of our opened issues.

**Comment by tonghuix** [comment]
Thank you very much!

**Comment by legoboyvdlp** [comment]
@gilbertohasnofb was this sound of any use to you?

**Comment by gilbertohasnofb** [comment]
Hi Lego, I took a look at the sound but I don't think I will be able to use it. I think the sound is too different to the 172, but also the length of the recording is too short (I can only make a decent loop if I have a long recording). Also, I think that a recording from inside the cockpit would be ideal as external recordings sound too different IMO. But thanks anyway!
