### ISSUE TITLE
Spiraling propwash effect

### ISSUE THREAD

**Issue by dany93** [c172p-team/c172p-detailed#947]
I wondered several times by observing the behavior, but now I'm almost sure that the spiraling propwash effect is not simulated by default in JSBSim (differently from the P-factor). Moreover, it is not included in Aeromatic. Thus, almost every aircraft is lacking it.
http://design-plane.blogspot.fr/2008/11/corkscrew-effect.html
This is the effect which makes the aircraft steer leftwards (yaw) at full thrust, low speed. Strongest when rolling on the runway, accelerating before takeoff.
This often disconcerts beginners in simulation. However, it is always present on single-propeller aircraft, more or less strong. From my IRL experience, strong enough to quickly take you out of of the runway if you don't correct it with the rudder pedals.

I think it is rather gentle in my proposal, compared with my observations (from memory) in RL ultralights. However, I do not know for the C172P. If C172p-like RL pilots could give their opinion, thank you. @tigert @Juanvvc @stuartbuchanan ?
Anyway, changing it later is easy.

My opinion is that merely feeling it before takeoff adds some realism.

**Comment by tigert** [comment]
Yeah, right rudder is needed. Also it is present on climbing and turning to left crosswind leg (low speed, climbing turn to left) where you need no left rudder at all — or actually you just slightly ease the right rudder a to keep the ball centered.

**Comment by tigert** [comment]
The rudder has a groumd-adjustable trim tab to set the cruise speed+power with pedals centered, ball centered. Low speed and high power setting does indeed require right rudder. It's not like it will fall out in a spin, the C172 is very forgiving, but you can see it from the slip ball and feel it in your butt.

**Comment by dany93** [comment]
Thank @tigert for this accurate description of the behavior.
All of it looks like that I've seen on ultralights.

> The rudder has a groumd-adjustable trim tab to set the cruise speed+power with pedals centered, ball centered

On ultralights, too.
Thank you for this, too.
I think I may add a trim-preset for the rudder.

Now, the question is 'how much effect', to be realistic enough and not discouraging the beginners. And for not being too harsh for those (many) who have no rudder pedals...

**Comment by tigert** [comment]
I think the answer is not very simple, because in addition to actually having proper flight controls in tye sim, also the actual travel movement can be different. Most joysticks have rather short movement so it is not too easy to fly accurately, and thus a small stick movement can be big in the simulated flight model. 

So whether it feels "real" and maps to the real-plane-muscle memory is not that simple. But the c172 is pretty good representation even now. I will see if I can find the time to try this out – though I don't have flight controls either, I fly with the mouse to get big enough yoke travel and thus accuracy.

**Comment by onox** [comment]
Fixed by PR #948
