### ISSUE TITLE
Back tip of the fuselage has strange reflection

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#966]
Back tip of the fuselage has strange reflection, it is brighter than the fuselage from nearly all angles.

![](https://user-images.githubusercontent.com/5700795/36178860-3039426a-1112-11e8-8090-15b9fef785b8.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb 
I'm not seeing this anymore, please confirm!

**Comment by gilbertohasnofb** [comment]
> I'm not seeing this anymore, please confirm!

I just did a pull on branch `issue-860` and I can confirm I am still experiencing this. Are you sure you pushed your fix?

**Comment by wlbragg** [comment]
I don't see that, I even used that livery to test it. It must be a certain lighting condition your in. Can you give me a clue as to your lighting, maybe location and weather settings? I can try again and move the aircraft around to all the compass directions and see if I can reproduce.
But,  look at the fairings, notice the edges who's faces are pointing the same direction as the tail section that is so bright. They appear to be just as bright only smaller so you don't notice it. I'm thinking it might just be the angle that is catching full sunlight? If it is, there is nothing we can do other than maybe changing the mesh at the tail to taper instead of go to such an extreme, flat angle.

**Comment by gilbertohasnofb** [comment]
Ok, so this is a test at LKCE

![fg-0](https://user-images.githubusercontent.com/5700795/36252989-3928b0e0-123e-11e8-9766-e71efea4f094.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/36252990-39459a98-123e-11e8-831b-fa8e2c49db3f.jpg)
![fg-2](https://user-images.githubusercontent.com/5700795/36252992-39d658d0-123e-11e8-98f1-41f3b5857cc3.jpg)
![fg-3](https://user-images.githubusercontent.com/5700795/36252993-3a780ffe-123e-11e8-9a2f-c036d4839bd4.jpg)

note that I have all shaders enabled:

![fg-4](https://user-images.githubusercontent.com/5700795/36253005-426e0f42-123e-11e8-989d-d39c251eac00.jpg)

This is another test at SAWB:

![fg-5](https://user-images.githubusercontent.com/5700795/36253016-49e31894-123e-11e8-94d9-d19c1effecfc.jpg)
![fg-6](https://user-images.githubusercontent.com/5700795/36253017-4a1c5780-123e-11e8-8a35-20f6edd17a7b.jpg)

So this is what I conclude from what I can observe on my side:

* bug is present regardless of the weather setup, real weather or weather preset
* bug is present regardless of airport

**Comment by gilbertohasnofb** [comment]
And just confirming, I am at `issue-860` and just did a `git pull`, for which I am told `Already up-to-date.`

**Comment by wlbragg** [comment]
@onox, do you see what @gilbertohasnofb  is seeing?

**Comment by wlbragg** [comment]
OK, I am able to recreate it on LKCE runway when the sun is rising. It is definitely the light reflecting, Use the accelerated time and watch it disappear to normal. I don't get the red tint your seeing, just the brightness. I don't know exactly what to do about it either. If you were to change the material settings and darken it up then the rest of the aircraft will do the same. Maybe make that part a separate mesh and make its material settings not so reflective.
I'm currently testing changes to blender settings to see what if anything I can do.

**Comment by wlbragg** [comment]
By looking at other like aircraft (c182s) I am almost positive this is a mesh design issue. It is simply flat in back and is catching the light accordingly. If you look at the back of the c182s in similar light conditions you can see the same thing only because of the tapering of the mesh it is a much smaller spot. I am going to try to reshape the tip of the tail but that is going to have an adverse affect on the liveries. Hopefully I can remap it to work OK.

**Comment by wlbragg** [comment]
Oh, you might ask why the c182p in fgaddon isn't as bad, it is because the mesh is screwed up back there and actually helping to break up the flat surface.

**Comment by wlbragg** [comment]
I am still not sure why your seeing "red" On mine I only see brightness.
I pushed a change to the ac just now. That is as much as I think I am going to be able to do. What I did was create several edge rings on the tail and tapered it like the c182s does. It may have helped some.
@gilbertohasnofb 
There is a test I would like you to try, start out on the runway (LKCE), morning, crank the wheel hard left (rudder hard right). with engine idling let off the brake and let the aircraft pivot until it is 90 deg on the runway (like blocking it sideways instead of trying to go down it). Watch what happens to the light on the tail face and the side of the fuselage facing the sun. You should see the light change to where the tail face (the one that is so bright) goes darker and the side of the fuselage turns just as bright as the tail face used to be.
Questions
Does that all look normal as that happens?
Does the side of the fuselage that is facing the sun start to get that red cast to it?

By the way, a side note. The rudder was really bent to port, I straightened it out.
![screenshot_2018-02-15_10-32-12](https://user-images.githubusercontent.com/11069680/36271325-e2e36c74-1243-11e8-8cb4-5fb75623ed24.png)

Test to see if the light changes as it should.
![fgfs-screen-022](https://user-images.githubusercontent.com/11069680/36271477-58cb3c82-1244-11e8-89d8-f143b0fdc682.png)

Before mesh tail change and rudder straightening
![fgfs-screen-019](https://user-images.githubusercontent.com/11069680/36271346-f8001526-1243-11e8-81f4-94f8a62c7d4e.png)

After  mesh tail change and rudder straightening
![fgfs-screen-023](https://user-images.githubusercontent.com/11069680/36271520-73e23e58-1244-11e8-94d5-9d20282abd10.png)

**Comment by wlbragg** [comment]
If this doesn't work for you I may make one more pass and ty to make the tail taper more extreme, as in over greater depth instead of so flat. But that requires changing the design of the tail and I need to look at some reference images to make sure I can even do that. WE NEED A NEW MODEL. There are so many issues it isn't funny.

Before
![screenshot_2018-02-15_10-32-47](https://user-images.githubusercontent.com/11069680/36272563-877762d8-1247-11e8-897d-7c2061f37f11.png)

After
![screenshot_2018-02-15_11-55-57](https://user-images.githubusercontent.com/11069680/36272578-936674bc-1247-11e8-827b-6bdc5d8ac6c4.png)

The nose sucks as you can see, but I remapped it so at least the whit eis gone.
![screenshot_2018-02-15_11-40-48](https://user-images.githubusercontent.com/11069680/36272611-a0a0c132-1247-11e8-9137-f9a3c6e05f9f.png)

Oh, before I forget, I need to only save the Blends when we're all done instead of every revision as they exponentially increase the size of the repository on ever revision and push.

**Comment by gilbertohasnofb** [comment]
> WE NEED A NEW MODEL. There are so many issues it isn't funny.

I know, @wlbragg, this has been a huge issue for sometime already. Creating a new model is a huge task, but at the same I just keep thinking of how much time we invested trying to fix the current one. There are so many issues indeed. My main one is actually the cockpit position which is really too low in relation to the fuselage and makes it look all wrong, completely ruining the main cockpit view in my opinion and looking very different and unrealistic from the real thing (this is my biggest annoyance with our model, I absolutely hate that cockpit view...). But with all this said, I truly appreciate what you have done and these efforts to improve the current model do not go unnoticed. Many, many thanks.

>  If you look at the back of the c182s in similar light conditions you can see the same thing only because of the tapering of the mesh it is a much smaller spot.

This is true, I just checked and the c182s suffers from the same issue:

![fg-3](https://user-images.githubusercontent.com/5700795/36285346-16c6d8f0-12a3-11e8-8154-8db723c54b0a.jpg)

Maybe this is just a limitation of how our reflection effect looks, unfortunately. We could perhaps try the best we can to minimize this issue at the back, but I see there is nothing much to be done.

> If this doesn't work for you I may make one more pass and ty to make the tail taper less extreme, as in over greater depth instead of so flat. But that requires changing the design of the tail and I need to look at some reference images to make sure I can even do that.

I would be happy to try whatever you can come up with! I just tried the newest modifications but the problem is still very apparent. I also noticed that the very back of the rudder is showing this issue, was there some modification to that object as well or that is just because my image below is zoomed?

![fg-0](https://user-images.githubusercontent.com/5700795/36285417-59ea8028-12a3-11e8-8c74-738c3a5b8d85.jpg)

> The nose sucks as you can see, but I remapped it so at least the white is gone.

But many thanks for fixing this, it looks a million times better!!!

**Comment by wlbragg** [comment]
>I would be happy to try whatever you can come up with! I just tried the newest modifications but the problem is still very apparent.

I have to possible ideas.
1) I'll try to do the taper thing I already mentioned
2) If that doesn't work ,what about changing the color or brightness of the texture in that spot. Like make it gray? Problem is all the liveries will have to be edited.

>I also noticed that the very back of the rudder is showing this issue, was there some modification to that object as well or that is just because my image below is zoomed?

I'm sure it was always there, your just now noticing it because it is zoomed in. I did modify the back edge of the rudder though because it was really bent. However I didn't change any dimensions, just straightened it.

From looking at your last screen shot at least I now know why you had what appeared to be a really red tint. I didn't realize it was the livery itself. At a distance it looked like only the tail face was red tinted.

**Comment by gilbertohasnofb** [comment]
> what about changing the color or brightness of the texture in that spot. Like make it gray? Problem is all the liveries will have to be edited and when not in the light it will maybe appear too dark?

Changing all liveries is not the problem (I would gladly do that if necessary), the problem is that I don't think this solution would look very good. As you pointed out, in a more uniform light the aircraft would have a dark tail. But on top of that, this would look unrealistic as the real liveries are painted in colour in those areas, e.g.:

![](https://flyingwisconsin.files.wordpress.com/2010/09/n7770g-at-eau.jpg)

Now something I noticed looking at this picture above is that we seem to have one more 3D model issue which might be the main contributor to this problem here. Notice how the fuselage gets thinner and straighter and leads directly to the rudder. In our case, we have those oval intersections of the fuselage ending and then starting a very straight rudder. perhaps if we were to deform a bit the fuselage so that it would lead into the rudder and there would be no normal surface pointing to the viewer from the angle of the screenshot above.

**Comment by wlbragg** [comment]
>In our case, we have those oval intersections of the fuselage ending and then starting a very straight rudder.

Interesting, your right. That goes hand in hand with my statement about changing the shape of the tail. The above picture verifies we technically or realistically could do this. Lets take that approach and see what we get.

**Comment by wlbragg** [comment]
OK, some new mesh to critique...
![fgfs-screen-027](https://user-images.githubusercontent.com/11069680/36319737-7f8bee78-1309-11e8-9472-28e4e51e58cc.png)

![fgfs-screen-028](https://user-images.githubusercontent.com/11069680/36319746-842912b2-1309-11e8-9e32-2b0785f2b07c.png)

![fgfs-screen-029](https://user-images.githubusercontent.com/11069680/36319751-89fe2b64-1309-11e8-9149-97a00556f214.png)

I am sure hoping this is close to finished!

**Comment by wlbragg** [comment]
One is volumetric grass and the other is the fur shader. There is two separate effect s in these shots.
https://forum.flightgear.org/viewtopic.php?f=6&t=23666
https://forum.flightgear.org/viewtopic.php?f=47&t=32183

**Comment by gilbertohasnofb** [comment]
> I am sure hoping this is close to finished!

This is looking really great!!! 👏

**Comment by wlbragg** [comment]
One more thing.
We talked about re-texturing the the end face of the tail. But we were concerned about making it darker. I remember seeing a picture on the Internet of the tail end of a c172p and it appeared to have mechanical stuff on the tail face. Also it was quit dark and in the shadows. My point being, a texture to simulate what that image portrayed might still be in order so when you are using rudder instead of seeing a shiny  face you would see something a little more realistic. I'll see if I can find the image for an example.

**Comment by wlbragg** [comment]
This kind of shows what I am talking about.
![tale1](https://user-images.githubusercontent.com/11069680/36339312-07762834-1388-11e8-8883-5aaeeca95895.png)

**Comment by gilbertohasnofb** [comment]
> it appeared to have mechanical stuff on the tail face

I will try to come up with something, I will push it to the 4X-CHV texture tonight and then it could be applied to all liveries. I will let you know.

**Comment by gilbertohasnofb** [comment]
@wlbragg Actually, I found some excellent pictures of the tail of a 172 and as you can see there is no need for a metal/mechanical texture:

![](https://disciplesofflight.com/wp-content/uploads/2016/09/2-skyhawk-auction-tail-strike.jpg)
![](https://disciplesofflight.com/wp-content/uploads/2016/09/2-skyhawk-auction-elevator-scratch.jpg)

**Comment by wlbragg** [comment]
That second picture is really helpful for the semicircle. I think I need to adjust ours a bit.

**Comment by dany93** [comment]
> Do you think the little rectangle below the horizontal stabilizer with what looks like a cable or wire sticking out of it going to the rudder is light wires or cable for the rudder movement? If for rudder movement, do you think then there is one on both sides of the fuselage?

For the C172P I don't know, but yes, I've seen that on Ultralights for the rudder, one cable on each side.
[SkyRanger](http://www.skyranger.co.uk/wp-content/uploads/2016/09/Swift-2-build-manual-0.1.pdf) p. PDF 92/283, Fig 116.
You will probably receive better responses, but just in case...

**Comment by gilbertohasnofb** [comment]
> Do you think the little rectangle below the horizontal stabilizer with what looks like a cable or wire sticking out of it going to the rudder is light wires or cable for the rudder movement? If for rudder movement, do you think then there is one on both sides of the fuselage?

I think this cable is on both sides, I will try to find a picture.

> I'm worrying. Will these 3D improvements not degrade the fps (fluidity)? Up to now, it was very good for such an aircraft.

We are barely adding any new polygons, we are mainly cleaning the current mesh. I am sure the performance difference will be negligible. Feel free to try the PR where this work is being done and report any performance issues if you see any.

**Comment by dany93** [comment]
> I think this cable is on both sides, I will try to find a picture.

Almost sure, the cable is on both sides.

**Comment by algefaen** [comment]
> Do you think the little rectangle below the horizontal stabilizer with what looks like a cable or wire sticking out of it going to the rudder is light wires or cable for the rudder movement? If for rudder movement, do you think then there is one on both sides of the fuselage?

Rudder control cable. Pretty symmetrical for both sides.

**Comment by gilbertohasnofb** [comment]
Here is an excellent close up of Airfoil Labs's Cessna 172 SP, though the SP is a much more modern aircraft than our P model:

![](https://www.x-plained.com/wp-content/uploads/2017/06/Airfoillabs-C172SP-63.jpeg)

Here is a photo of an older model, possibly even a P. You can magnify it to check the tail details:

![](https://i.stack.imgur.com/HMOAG.jpg)

**Comment by wlbragg** [comment]
>I'm worrying. Will these 3D improvements not degrade the fps (fluidity)? Up to now, it was very good for such an aircraft.

I think there has been very little net gain. Some of the change are actually cleaning up some really messed up mesh so it's possible we will see an improvement in performance.

If anyone is really worried about adding more eye candy such as rudder cables, etc. please do check performance along the way and speak out if you notice something that causes a hit.
