### ISSUE TITLE
Nose wheel buried in the ground

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#984]
![36568656-6a3e6032-17f0-11e8-9a11-48ba9327db46](https://user-images.githubusercontent.com/10434911/36572525-36a3c7d2-1834-11e8-8864-e4196934b368.png)

**Comment by legoboyvdlp** [comment]
Just noticed something else - I thought perhaps I had anti aliasing off, but there appears to be a normal map problem with the rivets on the part where the fuselage rises to meet the tail.

**Comment by gilbertohasnofb** [comment]
@wlbragg I also noticed those rivets around the tail but forgot to bring it up to you, would you prefer that we open a new issue for that or do we tackle this in the mega PR you are working on?

**Comment by wlbragg** [comment]
I'll be pushing any changes to the "mega PR" but if you want to make an issue that's OK too. I'll just refer to it in the pr ie: "Fixes XX".
Someone needs to post a screen shot highlighting the exact issue though.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp would you post the screenshot with the highlight?

**Comment by legoboyvdlp** [comment]
Unable, sorry @gilbertohasnofb  - on mobile, and it is 2am :)

If you can, please go ahead - I'm sure you can see it on the screenshot.

**Comment by wlbragg** [comment]
Done!
![fgfs-screen-001](https://user-images.githubusercontent.com/11069680/36576810-c8f613a4-1818-11e8-9087-484fe8bf1c53.png)

**Comment by legoboyvdlp** [comment]
Great :)

It's a small thing, but it really improves it!

You must be getting annoyed with gilberto and I, constantly noticing small things and expecting you to fix them... 😛

**Comment by wlbragg** [comment]
>It's a small thing, but it really improves it!

They may be small but they are really starting to add up to making this a nice model.

>You must be getting annoyed with gilberto and I, constantly noticing small things and expecting you to fix them

Nope, I actually appreciate your time and the time it take to identify these issues more than you know.

**Comment by legoboyvdlp** [comment]
I'll be checking out your branch soon to have a closer look to make more work for you 😜 

As for this issue, would it be an XML error or perhaps a jsbsim error with the point mass?

**Comment by wlbragg** [comment]
I hope you don't mind but I just fixed it. It is a little more complicated with this aircraft because of the gear changes we make. So you technically have to change it in c172p-ground-effects.xml.
I'll push this right now so you can see how we do it.
FYI: I have always preferred a very slight flattening of the bottom of the tire (as in real life), plus it lets you know you are actually on the ground. So if you notice a slight flattening, that is on purpose. For sure though the front tore was too low and the back tires weren't quite low enough. Let me know what you think when you see it.

**Comment by dany93** [comment]
I completely agree with you @wlbragg for the slight flattening of the bottom of the tires on the ground.

**Comment by dany93** [comment]
Tested your issue-737 (for the tires).
Accurate and nice @wlbragg!
?? Maybe the 36" nose wheel slightly more flattened ?

**Comment by wlbragg** [comment]
>Maybe the 36" nose wheel slightly more flattened ?

Yes, I didn't look at it but I am sure your right. You want to try?

**Comment by wlbragg** [comment]
If you are going to use the open PR branch to do this, make sure you pull my latest changes. I need to remember to watch out also for any pushes you do.

**Comment by legoboyvdlp** [comment]
Excellent! This should make it a lot better :)

And yes, a slight flattening on the tire does look realistic.

**Comment by dany93** [comment]
I was trying to understand (or remind) the c172p-ground-effects.xml file (I'm not very familiar with it).
If you don't mind, I'd prefer if you could do it. You will be much more rapid than I am. And I'm afraid of doing some mistake or conflict by pushing on your branch.
Otherwise I can try, but it will take some time and (??) be risky.
Another question: why different "Z" values for the left and right main wheels? It would be better to observe it with a copilot.

**Comment by wlbragg** [comment]
@dany93 Sorry, I didn't notice that was your post, I thought it was @legoboyvdlp and he indicated he was willing to try to do it originally. No problem, I'll take care of it as I just refreshed my memory as well.
As far as the different Z values for left and right, I suppose if you think it is appropriate or necessary I can take the happy medium and make them the same. But what was happening is one tire was slightly different in depth on the pavement as the other. I guess I could even adjust the tire and strut to make them match. I'll fix it using the same Z. Why do you think it is significant to have that slight  anomaly?

**Comment by wlbragg** [comment]
>I just wondered how and why it happened that it had been necessary.

I see, if I had to guess, I'd say it is caused by a slight discrepancy in the left and right struts and/or wheel model position of the mesh.

I never really gave any thought as to the affect the contact point being asymmetrical might have on performance, especially something as small as what we are talking about.

My only desire was to make the visual of the wheels on the surface symmetrical which as it stands now requires a .2" (inch) difference between the two. One at 15.1 the other 15.3.
Putting them both to 15.2 is good enough as far as I am concerned but if you look closely you can see a difference.

As far as weight is concerned, It doesn't appear to make much of a difference in the flatness of the tire, more so the spring. In fact I tried adding max pilot + left passenger then max copilot + right passenger and it really doesn't appear to make much of a difference and the pilot side is always less flat than the copilot side.

**Comment by dany93** [comment]
>  I'd say it is caused by a slight discrepancy in the left and right struts and/or wheel model position of the mesh.

Fixing such a thing in Blender would not be a small work.
I'm basic with Blender, but I cannot see any difference in Z coordinates between the right and left main wheels. Reassuring...

> I never really gave any thought as to the affect the contact point being asymmetrical might have on performance, especially something as small as what we are talking about.

I agree (for the FDM of course, these very small differences).

> My only desire was to make the visual of the wheels on the surface symmetrical which as it stands now requires a .2" (inch) difference between the two. One at 15.1 the other 15.3.
Putting them both to 15.2 is good enough as far as I am concerned but if you look closely you can see a difference.

Your desire is fulfilled. I don't understand why this difference but searching and fixing it probably requires too much time. Minor issue, which may be fixed later if someone feels a trouble.
IMO do as you prefer, no problem.

More thinking...

> As far as weight is concerned, It doesn't appear to make much of a difference in the flatness of the tire, 

About the position difference (slight flattening) seen on the ground vs the weight or spring compression, this should give no visible effect, the 3D animation is here to follow the displacements. But this kind of animation is very tricky to tune. The fact that you see no difference is a good clue...
